# Generated by Django 3.0.6 on 2020-06-06 21:24

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', tinymce.models.HTMLField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255)),
                ('front_page', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
