# Generated by Django 3.0.6 on 2020-06-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200610_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='event',
            name='front_page',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
    ]
