# Generated by Django 3.0.6 on 2020-06-13 18:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200612_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.CreateModel(
            name='Project_post',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post_number', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(default='c662f6ec-672b-469a-b42c-4b78f33e51d1', on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
