# Generated by Django 3.0.6 on 2020-06-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200613_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_post',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='project_post',
            name='uuid',
        ),
        migrations.AddField(
            model_name='project_post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_post',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
