# Generated by Django 3.0.6 on 2020-06-17 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='id',
        ),
        migrations.AddField(
            model_name='bio',
            name='bid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
