# Generated by Django 3.0.6 on 2020-06-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0002_auto_20200617_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='headshot',
            field=models.ImageField(upload_to='headshot/'),
        ),
    ]
