# Generated by Django 3.0.6 on 2020-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0004_auto_20200617_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='past',
            field=models.BooleanField(default=False),
        ),
    ]
